// flow-typed signature: 7d98081b0660b0608d6093787bac3092
// flow-typed version: <<STUB>>/rollup-plugin-terser_v^1.0.1/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-terser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-terser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'rollup-plugin-terser/index' {
  declare module.exports: $Exports<'rollup-plugin-terser'>;
}
declare module 'rollup-plugin-terser/index.js' {
  declare module.exports: $Exports<'rollup-plugin-terser'>;
}
